name: Testing

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup and install standard requirements
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install .
        python3 -m pip list

    - name: Install dev requirements
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        python3 -m pip install '.[dev]'
        python3 -m pip list

    - name: Run tests
      shell: bash -l {0}
      run: |
        set -vxeuo pipefail
        coverage run --source=autojob -m pytest -v
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -f .coverage
